# Generated by Django 6.1.1 on 2026-09-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_application_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
