# Generated by Django 6.1.1 on 2026-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.FloatField(default=0),
        ),
    ]
